### ISSUE TITLE
I can't compile this plugin for UE5

### ISSUE THREAD

**Issue by GameDevMurras** [Acren/UE4-RichTextBlock-Inline-Decorator#2]
I think something big changed inside Unreal Engine source because I cannot compile doing simple adjustments like changing the project version to "5.0.0" or adjusting SWidget function

**Comment by acren** [comment]
Hi, try latest, should be fixed in this commit: https://github.com/Acren/RichTextBlockInlineDecorator/commit/8cba47e615901b3417e579d0398aee0ef793b454
